name: "Tests with Containers"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev
      - hotfixes

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: true
      matrix:
        python-version: ['3.7','3.8','3.9','3.10']
        platform: ['core', 'full'] # ['pycuda', 'cupy']
    name: Testing ${{ matrix.platform }}/python=${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ptypy_${{ matrix.platform }}_py${{ matrix.python-version }}_dev:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: runtime
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            PLATFORM=${{ matrix.platform }}
      - name: Run test inside container
        run: docker run ptypy_${{ matrix.platform }}_py${{ matrix.python-version }}_dev:latest pytest

  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
          exclude: "./archive,./benchmark"
          args: "--count --select=E9,F63,F7,F82 --show-source --statistics"
